### ISSUE TITLE
Further information would be great

### ISSUE THREAD

**Issue by danisowa** [juanferrla/rotex_solaris#1]
Hello,
very cool work and i'm really inerested in impementing this with my solaris.

Can you share some more details in your documentation?
Helpful / useful would be

- put your ESPHome config to repo
- Add your cool draw.io image to the repo
- Explain short where you grab the 5V on Solaris Control panel i found the 3,5mm jack but no connection to get the 5V

Thank you very much!

**Comment by juanferrla** [comment]
Hi, 

- I added the ESP32 code. It's experimental but it works. Added drawio file too.
- The 3,5mm jack provides 5v and you need to transform this 5V into 3.3v to avoid damaging the ESP32 board.

Comments or questions are welcome!!

**Comment by danisowa** [comment]
Thanks for your feedback. In the meantime i created my own project, based on tasmota. Reason is the custom lambda stuff seems to be deprecated, so i decided to implement it on tasmota base with berry script.
I was inspired by your project and created my own drawing :-)

if you are interested you can have a look here
https://github.com/BitSWB/esp32_tasmota_rotex_solaris_moitor
